# Generated by Django 6.0.2 on 2026-02-09 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('app_label', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='auditlog_ac_created_f7ddc5_idx'), models.Index(fields=['action', 'created_at'], name='auditlog_ac_action_6d89fb_idx'), models.Index(fields=['user', 'created_at'], name='auditlog_ac_user_id_79b774_idx'), models.Index(fields=['device_id', 'created_at'], name='auditlog_ac_device__d016d2_idx')],
            },
        ),
    ]
