# Generated by Django 6.0.2 on 2026-02-09 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('other_names', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expelled', 'Expelled'), ('deceased', 'Deceased'), ('unknown', 'Unknown')], default='active', help_text='Current enrollment status', max_length=10, null=True)),
                ('photo', models.ImageField(blank=True, default=None, help_text='Upload a student photo', null=True, upload_to='student_photos/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('schoolpay_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('Lin', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('level', models.CharField(blank=True, choices=[('NURSERY', 'Nursery'), ('PRIMARY', 'Primary'), ('OLEVEL', 'O-Level'), ('ALEVEL', 'A-Level')], max_length=20, null=True)),
                ('student_type', models.CharField(blank=True, choices=[('DAY', 'Day Scholar'), ('BOARDING', 'Boarding')], default='DAY', max_length=10, null=True)),
                ('uce_index_number', models.CharField(blank=True, default='', max_length=50)),
                ('uace_index_number', models.CharField(blank=True, default='', max_length=50)),
                ('parent_name', models.CharField(blank=True, default='', max_length=255)),
                ('parent_contact', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schoolprofile.schoolclass')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schoolprofile.stream')),
            ],
        ),
        migrations.CreateModel(
            name='ParentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=50)),
                ('relationship', models.CharField(blank=True, default='', max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False)),
                ('class_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_subjects', to='schoolprofile.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'class_subject')},
            },
        ),
    ]
