# Generated by Django 5.2.9 on 2026-01-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/logo/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='school/banner/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('school_type', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=50)),
                ('ownership', models.CharField(choices=[('private', 'Private'), ('government', 'Government'), ('ngo', 'NGO')], default='private', max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('academic_year_start', models.DateField(blank=True, null=True)),
                ('academic_year_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('number_of_papers', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolprofile.level')),
            ],
            options={
                'unique_together': {('level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolprofile.schoolclass')),
            ],
            options={
                'unique_together': {('school_class', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('min_students', models.PositiveIntegerField(default=0)),
                ('max_students', models.PositiveIntegerField(default=60)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolprofile.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolprofile.subject')),
            ],
            options={
                'unique_together': {('school_class', 'subject')},
            },
        ),
    ]
